leftnav:
- identifier: beb27c05-4f24-4fb0-613e-d5f405be85d7
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: dccc2763-0584-1e26-0257-f07a8b186340
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 7f4244d7-236a-8966-c7c8-76c85c7f5fd9
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 07a53e32-68bc-d0f1-3aa5-4168ebe767ad
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
